# TCL File Generated by Component Editor 16.1
# Sat May 27 16:43:32 BRT 2017
# DO NOT MODIFY


# 
# fut "fut" v1.0
#  2017.05.27.16:43:32
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.0


# 
# module fut
# 
set_module_property DESCRIPTION ""
set_module_property NAME fut
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fut
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL iir_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file iir_avalon.vhd VHDL PATH ../src/iir_avalon.vhd TOP_LEVEL_FILE
add_fileset_file iir_core.vhd VHDL PATH ../src/iir_core.vhd
add_fileset_file iir_package.vhd VHDL PATH ../src/iir_package.vhd


# 
# parameters
# 
add_parameter NBITS_ADDR INTEGER 16
set_parameter_property NBITS_ADDR DEFAULT_VALUE 16
set_parameter_property NBITS_ADDR DISPLAY_NAME NBITS_ADDR
set_parameter_property NBITS_ADDR TYPE INTEGER
set_parameter_property NBITS_ADDR UNITS None
set_parameter_property NBITS_ADDR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_ADDR HDL_PARAMETER true
add_parameter NBITS_ADDR_MASTER INTEGER 32
set_parameter_property NBITS_ADDR_MASTER DEFAULT_VALUE 32
set_parameter_property NBITS_ADDR_MASTER DISPLAY_NAME NBITS_ADDR_MASTER
set_parameter_property NBITS_ADDR_MASTER TYPE INTEGER
set_parameter_property NBITS_ADDR_MASTER UNITS None
set_parameter_property NBITS_ADDR_MASTER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_ADDR_MASTER HDL_PARAMETER true
add_parameter NBITS_ADDR_SLAVE INTEGER 7 ""
set_parameter_property NBITS_ADDR_SLAVE DEFAULT_VALUE 7
set_parameter_property NBITS_ADDR_SLAVE DISPLAY_NAME NBITS_ADDR_SLAVE
set_parameter_property NBITS_ADDR_SLAVE TYPE INTEGER
set_parameter_property NBITS_ADDR_SLAVE UNITS None
set_parameter_property NBITS_ADDR_SLAVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_ADDR_SLAVE DESCRIPTION ""
set_parameter_property NBITS_ADDR_SLAVE HDL_PARAMETER true
add_parameter NBITS_DATA_MASTER INTEGER 16
set_parameter_property NBITS_DATA_MASTER DEFAULT_VALUE 16
set_parameter_property NBITS_DATA_MASTER DISPLAY_NAME NBITS_DATA_MASTER
set_parameter_property NBITS_DATA_MASTER TYPE INTEGER
set_parameter_property NBITS_DATA_MASTER UNITS None
set_parameter_property NBITS_DATA_MASTER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_DATA_MASTER HDL_PARAMETER true
add_parameter NBITS_DATA_SLAVE INTEGER 32
set_parameter_property NBITS_DATA_SLAVE DEFAULT_VALUE 32
set_parameter_property NBITS_DATA_SLAVE DISPLAY_NAME NBITS_DATA_SLAVE
set_parameter_property NBITS_DATA_SLAVE TYPE INTEGER
set_parameter_property NBITS_DATA_SLAVE UNITS None
set_parameter_property NBITS_DATA_SLAVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NBITS_DATA_SLAVE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset_sink
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 1
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_chipselect chipselect Input 1
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_address address Input nbits_addr_slave
add_interface_port slave slave_writedata writedata Input nbits_data_slave
add_interface_port slave slave_waitrequest waitrequest Output 1
add_interface_port slave slave_readdatavalid readdatavalid Output 1
add_interface_port slave slave_readdata readdata Output nbits_data_slave
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_waitrequest waitrequest Input 1
add_interface_port avalon_master master_address address Output nbits_addr_master
add_interface_port avalon_master master_write write Output 1
add_interface_port avalon_master master_writedata writedata Output nbits_data_master

